# Dependabot will run on day 23 of each month at 01:27 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "27 1 23 * *"
    assignees:
      - "lvogt"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 15
